---
title: "Practico_0"
output: pdf_document
date: "2023-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
```


```{r}
#Ejercicio 1
#B

x=seq(-5,5,0.001)

p_norm = function(x) {
  (1/sqrt(2*pi))*exp((-x^2)/2)
}

x_1=seq(-5,5,0.01)
```


```{r}

d=p_norm(x)

ggplot() + geom_point(aes(x=x,y=d))

```


```{r}
#Ejercicio 1
#D
d_norm_sig = function(x,y,z) {
  (1/(sqrt(2*pi)*z))*exp((-((x-y)/z)^2)/2)
}
#f(x; µ, σ)
#1 - µ = 0 y σ = 1
#2 - µ = 5 y σ = 1
#3 - µ = 5 y σ = 4

plot_1=d_norm_sig(x_1,0,1)
plot_2=d_norm_sig(x_1,5,1)
plot_3=d_norm_sig(x_1,5,4)


ggplot() + geom_point(aes(x=x_1,y=plot_1))
ggplot() + geom_point(aes(x=x_1,y=plot_2))
ggplot() + geom_point(aes(x=x_1,y=plot_3))

```
```{r}
#Ejercicio 2
#

cauchy= function (x,y) {
  (1/pi)*(1/(1+(x-y)^2))
}

plot_c=cauchy(x_1,0)


ggplot() + geom_point(aes(x=x_1,y=plot_c))

```

```{r}
#Ejercicio 3
#
binormal= function (x,p,n)
{choose(n,x)*(p^x)*((1-p)^(n-x))
}

#1 - n = 50 y p = 0,2
#2 - n = 50 y p = 0,8
#3 - n = 50 y p = 0,5

binormal(1,0.2,50)


```

