---
title: "Untitled"
output: pdf_document
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }
set.seed(1)

u = runif(10)

f = function (u,p) {
  as.numeric(u>p)
}

f(u,p=0.5)
```

## Clase 13/11

# Simular una poisson

```{r pressure, echo=FALSE}

lamda=2

out = sapply(1:100, function(i) {
  u = runif(10)
  x = -log(1-u)/lamda  
  y=cumsum(x)
  length(which(y<=1))
})


set.seed(1)

mean(rpois(100,2))
var(rpois(100,2))

```

## Simular una NORMAL

Generamos uniformes 0-1  

```{r}
set.seed(1)
u = runif(100)

mean(u)

sum(u)- (length(u)*0.5) #Esperanza

```

```{r}
M <- 1.5 # valor de la constante de normalizacion
# valores para comenzar el while
U <- Inf
Y <- 0.5
# contador de simulaciones
j <-0
while (U > dbeta (Y,2,2)/(M*dunif(Y,0,1))) {
Y <- runif(1)
U <- runif(1)
j <-j +1
print(c(j,U))
}


sim_beta<-function(n,alfa,beta) {
xM<-(alfa-1)/(alfa + beta -2) # valor de la constante de normalizacion
M <- dbeta( xM , alfa , beta )
x <- rep(0 , n )
# vector para almacenar las simulaciones
J <-0
# contador para registrar el N total de simulaciones
for ( i in 1: n ) {
# valores para comenzar el while
U <- Inf
Y <- 0.5
# contador de simulaciones
j <-0
while (U > dbeta(Y , alfa , beta ) / ( M * dunif(Y ,0 ,1) ) ) {
Y <- runif(1)
U <- runif(1)
j <-j +1
}
x[i]<-Y
J <-J + j
}
print( J )
return( x )
}


sim_beta(n=1000,2,2)

```

```{r}

plot(x=seq(0,5,0.01) , dgamma(x=seq(0,5,0.01),shape=2,scale=0.5))

f=function(x) {dgamma(x,2,scale=0.5)}

M=optimise(f,interval=c(0,5),maximum = TRUE)

M
plot(x=seq(0,5,0.01),f(x=seq(0,5,0.01)))
abline (x=M$maximum)


```


