---
title: "Optimización"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sección Áurea

## Construyo una función de ejemplo


```{r}

f1= function(x) x-x*log(x)-exp(-x)


x=seq(0,5,0.1)

plot(x,f1(x),type='l')
abline(h=0)

```

Construyo la función para iterar


```{r}

while (amplitud>tol & iter<maxiter){
      if( x_d - x_m > x_m - x_i)
      {
          #se elije x_k en el intervalo (x_m , x_d)
          if(f(x_k) > f(x_m))
      {
      x_i = x_m
      x_m = x_k
    } else { x_d = x_k}
    }
    else
        {
          #se elije x_k en el intervalo (x_i , x_m)
           if (f(x_k) > f(x_m))
          {
            x_d = x_m
            x_m = x_k
          } else x_i = x_k
    }
# por ultimo se actualiza la condicion y se incrementa el iterador
    }
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
