---
title: "Trabajo Final de Introducción a la Estadística Computacional"
subtitle: "Minimización de pérdida al aplicar un plan de simplificación"
author:
- "Lucas Bizoso"
- "Germán Miranda"
date: "2023-11-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Situación actual

```{r }
set.seed(1)
n_ini=80

## Genero los vectores iniciales de precios y cantidades

p_actuales=c()
q_actuales=c()

while (length(p_actuales)!=n_ini ) {
  
p_actuales=as.integer(runif(n_ini,200,3000))

}

q_actuales=as.integer(runif(n_ini,1,3000))

p_actuales

## Ordeno el vector inicial de precios de menor a mayor

p_actuales=p_actuales[order(p_actuales)]

I_Inicial=sum(p_actuales*q_actuales)

y=p_actuales*q_actuales

plot(p_actuales,y)

```


\newpage

# Simulación para un caso puntual

```{r}
#Genero un nuevo vector Aleatorio de precios nuevos

#Queremos finalizar con 20 planes, simulo 18 y los dos restantes los fijos con el máximo y el mínimo de los actuales

n_final=18

p_nuevos_tmp=as.integer(runif(n_final,min(p_actuales),max(p_actuales)))

#Concateno los 18 simulados, con el máximo y mínimo

p_nuevos=c(p_nuevos_tmp,min(p_actuales),max(p_actuales))

#Ordeno el vector de menor a mayor
p_nuevos=p_nuevos[order(p_nuevos)]


q_nuevos=c()

#Fijo la cantidad de Q para cada uno de los planes nuevos

for (j in 1:length(p_nuevos)) {
  q=0
  for (i in 1:length(p_actuales)) {
      if (p_actuales[i]>=p_nuevos[j]) {
          q = q + q_actuales[i]
          q_nuevos[j]= q
       }
    }
}

for (i in 1:(length(q_nuevos)-1)) {
  q_nuevos[[i]] = q_nuevos[[i]] - q_nuevos[[i+1]] 
}


I_Final=sum(p_nuevos*q_nuevos)

y_final=p_nuevos*q_nuevos

# Porcentaje de pérdida

((I_Final-I_Inicial)/I_Inicial)*100

```

\newpage

#Simulación para varios experimentos 




\newpage

#SCRIPT AUXILIAR

```{r,eval=FALSE}

qq2=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp2){
    qq2= qq2 +q_actuales[[k]]
  }
}
qq2

qq3=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp3){
    qq3= qq3 +q_actuales[[k]]
  }
}
qq3

qq2= qq2-qq3

qq1 = qq1 -qq2 -qq3
```


EJEMPLO CON CASOS LIMITADOS

```{r}

p1 = 200 
p2 = 350
p3 = 500
p4 = 900
p5 = 1500

p_actuales = c(p1,p2,p3,p4,p5)

q1=5050
q2=700
q3=1000
q4=200
q5=700

q_actuales = c(q1,q2,q3,q4,q5)

sum(q_actuales)

Ibase = p1*q1 + p2*q2 + p3*q3 + p4*q4 + p5*q5

pn1=200
pn2=400
pn3=900

p_nuevos = c (pn1,pn2,pn3)

p_nuevos=as.integer(runif(20,min(p_actuales),max(p_actuales)))

q_nuevos=c()

for (j in 1:length(p_nuevos)) {
  q=0
  for (i in 1:length(p_actuales)) {
      if (p_actuales[i]>=p_nuevos[j]) {
          q = q + q_actuales[i]
          q_nuevos[j]= q
       }
    }
}

for (i in 1:(length(q_nuevos)-1)) {
  q_nuevos[[i]] = q_nuevos[[i]] - q_nuevos[[i+1]] 
}

Ifinal=sum(p_nuevos*q_nuevos)

```
