---
title: "Proyecto Final"
author: "Grupo M"
date: "2023-11-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}

p1 = 200 
p2 = 350
p3 = 500
p4 = 900
p5 = 1500

p_actuales = c(p1,p2,p3,p4,p5)

q1=5050
q2=700
q3=1000
q4=200
q5=700

q_actuales = c(q1,q2,q3,q4,q5)

sum(q_actuales)

I = p1*q1 + p2*q2 + p3*q3 + p4*q4 + p5*q5


p_nuevos = list (200,400,900)


pp1 = 200 
pp2 = 400
pp3 = 1000


qq1=0
for (i in 1:length(p_actuales)) {
  if (p_actuales[[i]]>=pp1){
    qq1= qq1 +q_actuales[[i]]
  }
}
qq1


qq2=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp2){
    qq2= qq2 +q_actuales[[k]]
  }
}
qq2

qq3=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp3){
    qq3= qq3 +q_actuales[[k]]
  }
}
qq3

qq2= qq2-qq3

qq1 = qq1 -qq2 -qq3


Ifinal = pp1*qq1 + pp2*qq2 + pp3*qq3

I
Ifinal
Ifinal-I



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
