---
title: "Proyecto Final"
author: "Grupo M"
date: "2023-11-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


EJEMPLO CON CASOS LIMITADOS

```{r}

p1 = 200 
p2 = 350
p3 = 500
p4 = 900
p5 = 1500

p_actuales = c(p1,p2,p3,p4,p5)

q1=5050
q2=700
q3=1000
q4=200
q5=700

q_actuales = c(q1,q2,q3,q4,q5)

sum(q_actuales)

Ibase = p1*q1 + p2*q2 + p3*q3 + p4*q4 + p5*q5

pn1=200
pn2=400
pn3=900

p_nuevos = c (pn1,pn2,pn3)

p_nuevos=as.integer(runif(20,min(p_actuales),max(p_actuales)))

q_nuevos=c()

for (j in 1:length(p_nuevos)) {
  q=0
  for (i in 1:length(p_actuales)) {
      if (p_actuales[i]>=p_nuevos[j]) {
          q = q + q_actuales[i]
          q_nuevos[j]= q
       }
    }
}

for (i in 1:(length(q_nuevos)-1)) {
  q_nuevos[[i]] = q_nuevos[[i]] - q_nuevos[[i+1]] 
}

Ifinal=sum(p_nuevos*q_nuevos)

```
EJEMPLO ALEATORIO

```{r}
set.seed(1)
n_ini=100
p_actuales=as.integer(runif(n_ini,min=200,max=3000))
q_actuales=as.integer(runif(n_ini,1,1000))

p_actuales

o_pact=order(p_actuales)
p_actuales=p_actuales[o_pact]
p_actuales
sum(p_actuales*q_actuales)

p_nuevos=as.integer(runif(20,min(p_actuales),max(p_actuales)))

o_pnuev=order(p_nuevos)
p_nuevos=p_nuevos[o_pnuev]
p_nuevos

q_nuevos=c()

for (j in 1:length(p_nuevos)) {
  q=0
  for (i in 1:length(p_actuales)) {
      if (p_actuales[i]>=p_nuevos[j]) {
          q = q + q_actuales[i]
          q_nuevos[j]= q
       }
    }
}

q_nuevos
for (i in 1:(length(q_nuevos)-1)) {
  q_nuevos[[i]] = q_nuevos[[i]] - q_nuevos[[i+1]] 
}


sum(q_actuales)
sum(q_nuevos)

```


SCRIPT AUXILIAR

```{r}

qq2=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp2){
    qq2= qq2 +q_actuales[[k]]
  }
}
qq2

qq3=0
for (k in 1:5) {
  if (p_actuales[[k]]>=pp3){
    qq3= qq3 +q_actuales[[k]]
  }
}
qq3

qq2= qq2-qq3

qq1 = qq1 -qq2 -qq3
```

